name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: EasyPodcast ${{ github.ref_name }}
          body: |
            Vea [CHANGELOG.md](https://github.com/educollado/easypodcast/blob/${{ github.ref_name }}/CHANGELOG.md) para detalles de esta versión.
          files: |
            docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
